name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      ## MacOS Setup
      - name: install lazarus (Mac)
        if: matrix.os == 'macos-latest'
        run: |
          brew install lazarus
          echo /Applications/Lazarus >> $GITHUB_PATH

      ## Linux Setup

      - name: install lazarus (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install lazarus


      ## Windows Setup

      - name: install make (windows)
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install make

      - name: install 32-bit lazarus (windows)
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install --x86 lazarus

      # https://stackoverflow.com/a/64831469
      - name: add lazarus to path (windows)
        if: matrix.os == 'windows-latest'
        run: echo "C:\lazarus" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      ## Build

      - run: lazbuild --version

      - name: fpc version
        run: fpc -iW
        if: matrix.os != 'windows-latest'

      - uses: actions/checkout@v2

      - run: make clean

      - run: make smartset_master
      - run: make smartset_master_office
      # - run: make smartset_adv2
      # - run: make smartset_fsedge
      # - run: make smartset_savant_elite
      - run: make smartset_tko
      - run: make smartset_rgb


      - uses: actions/upload-artifact@v1
        with:
          name: SmartSetMaster-${{ runner.os }}
          path: SmartSetMaster

      - uses: actions/upload-artifact@v1
        with:
          name: SmartSetMasterOffice-${{ runner.os }}
          path: SmartSetMasterOffice

      - uses: actions/upload-artifact@v1
        with:
          name: SmartSetAdv2-${{ runner.os }}
          path: SmartSetAdv2

      - uses: actions/upload-artifact@v1
        with:
          name: SmartSetFSEdgePro-${{ runner.os }}
          path: SmartSetFSEdgePro

      - uses: actions/upload-artifact@v1
        with:
          name: SmartSetSavantElite-${{ runner.os }}
          path: SmartSetSavantElite
